import path from 'path';
import {version} from '../../package.json';

export default function(fs, config) {

  /// === general ===

  fs.write(
    '.gitignore',
    `npm-debug.log\nnode_modules\n${path.join(config.scripts.dest, '*')}\n${path.join(config.styles.dest, '*')}`
  );

  fs.writeJSON(
    '.tradierc',
    config
  );

  fs.writeJSON(
    'package.json',
    {
      name: path.basename(process.cwd()),
      private: true,
      devDependencies: {
        tradie: `^${version}`
      },
      scripts: {
        build: 'tradie build',
        test: 'tradie test'
      }
    }
  );

  fs.write(
    'index.html',
    `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Tradie Project</title>
  <link rel="stylesheet" href="./dist/index.css"/>
</head>
<body>
  <h4>Tradie Project</h4>
  <p>This project has been generated by <code>tradie</code>.</p>
  <script src="./dist/index.js"></script>
</body>
</html>
`
  );

  // === scripts ===

  fs.writeJSON(
    '.eslintrc',
    {
      env: {
        browser: true,
        mocha: true
      },
      extends: 'eslint:recommended'
    }
  );

  fs.write(
    path.join(config.scripts.src, 'index.js'),
    ''
  );

  fs.write(
    path.join(config.scripts.src, 'index.test.js'),
    ''
  );

  // === styles ===

  fs.write(
    path.join(config.styles.src, 'index.scss'),
    ''
  );

}